"""
Context exporter — renders compressed project context into editor-native formats.

Formats:
  claude-md      → CLAUDE.md     (Claude Code)
  cursorrules    → .cursorrules  (Cursor)
  windsurfrules  → .windsurfrules (Windsurf)
"""

from __future__ import annotations

from pathlib import Path


def export_claude_md(ctx: dict, project_root: Path) -> str:
    """Render context dict as CLAUDE.md for Claude Code."""
    name = ctx.get("project", project_root.name)
    lang = ctx.get("language", "unknown")
    fw = ctx.get("frameworks", "none")
    db = ctx.get("database", "none")
    auth = ctx.get("authentication", "none")
    api = ctx.get("api_style", "none")
    arch = ctx.get("architecture", "unknown")
    deploy = ctx.get("deployment", "none")
    tests = ctx.get("test_framework", "none")
    health = ctx.get("health_score")

    lines = [
        f"# {name}",
        "",
        "> Context auto-generated by [ProjectMind AI](https://github.com/Aaravkhanal/llm-reviewer).  ",
        "> Regenerate: `projectmind export --format claude-md`",
        "",
        "## Stack",
        "",
        f"| | |",
        f"|---|---|",
        f"| **Language** | {lang} |",
        f"| **Frameworks** | {fw} |",
        f"| **Database** | {db} |",
        f"| **Auth** | {auth} |",
        f"| **API style** | {api} |",
        f"| **Architecture** | {arch} |",
        f"| **Tests** | {tests} |",
        f"| **Deployment** | {deploy} |",
    ]

    if health is not None:
        lines.append(f"| **Health score** | {health}/10 |")

    entry_points = ctx.get("entry_points", [])
    if entry_points:
        lines += ["", "## Entry Points", ""]
        for ep in entry_points:
            lines.append(f"- `{ep}`")

    coding_style = ctx.get("coding_style", [])
    if coding_style:
        lines += ["", "## Coding Conventions", ""]
        for rule in coding_style:
            lines.append(f"- {rule}")

    decisions = ctx.get("decisions", [])
    if decisions:
        lines += ["", "## Architecture Decisions", "", "_Do not re-litigate these._", ""]
        for d in decisions:
            lines.append(f"- {d}")

    errors = ctx.get("known_errors", [])
    if errors:
        lines += ["", "## Known Issues to Avoid", ""]
        for e in errors:
            lines.append(f"- {e}")

    patterns = ctx.get("patterns", [])
    if patterns:
        lines += ["", "## Established Patterns", ""]
        for p in patterns:
            lines.append(f"- {p}")

    recent = ctx.get("recent_tasks", [])
    if recent:
        lines += ["", "## Recent Tasks", ""]
        for t in recent:
            lines.append(f"- {t}")

    lines += [
        "",
        "## Common Commands",
        "",
        "```bash",
        "projectmind analyze       # health score + security scan",
        "projectmind graph build   # rebuild knowledge graph",
        "projectmind watch         # auto-update context on file changes",
        "projectmind generate-prompt --task '...'  # enriched agent prompt",
        "```",
        "",
    ]

    return "\n".join(lines)


def export_cursorrules(ctx: dict, project_root: Path) -> str:
    """Render context dict as .cursorrules for Cursor."""
    name = ctx.get("project", project_root.name)
    lang = ctx.get("language", "unknown")
    fw = ctx.get("frameworks", "none")
    db = ctx.get("database", "none")
    arch = ctx.get("architecture", "unknown")

    parts = [
        f"You are working on **{name}** — a {lang} project.",
        "",
        f"**Stack:** {fw}  |  **DB:** {db}  |  **Architecture:** {arch}",
        "",
    ]

    coding_style = ctx.get("coding_style", [])
    if coding_style:
        parts += ["**Always follow these conventions:**", ""]
        for rule in coding_style:
            parts.append(f"- {rule}")
        parts.append("")

    decisions = ctx.get("decisions", [])
    if decisions:
        parts += ["**Architecture decisions (settled — do not re-litigate):**", ""]
        for d in decisions:
            parts.append(f"- {d}")
        parts.append("")

    errors = ctx.get("known_errors", [])
    if errors:
        parts += ["**Known bugs to avoid:**", ""]
        for e in errors:
            parts.append(f"- {e}")
        parts.append("")

    patterns = ctx.get("patterns", [])
    if patterns:
        parts += ["**Established patterns:**", ""]
        for p in patterns:
            parts.append(f"- {p}")
        parts.append("")

    parts += [
        "_Context generated by ProjectMind AI. Regenerate: `projectmind export --format cursorrules`_",
    ]

    return "\n".join(parts)


_FORMAT_MAP = {
    "claude-md":     ("CLAUDE.md",        export_claude_md),
    "cursorrules":   (".cursorrules",     export_cursorrules),
    "windsurfrules": (".windsurfrules",   export_cursorrules),  # same format, different file
}


def export(project_path: str, fmt: str) -> tuple[Path, str]:
    """
    Run the compressor and write the context in the requested format.
    Returns (output_path, content).
    """
    if fmt not in _FORMAT_MAP:
        raise ValueError(f"Unknown format: {fmt!r}. Choose from: {list(_FORMAT_MAP)}")

    from backend.core.compression.compressor import Compressor
    root = Path(project_path).resolve()
    ctx = Compressor(str(root)).compress()

    filename, renderer = _FORMAT_MAP[fmt]
    content = renderer(ctx, root)
    out_path = root / filename
    out_path.write_text(content, encoding="utf-8")
    return out_path, content
