"""
CI Health Gate — reads health_score.json and fails if thresholds are violated.

Used by the GitHub Action (projectmind-health-gate/action.yml) and
can be called directly:
  python -m backend.ci.gate --path . --security-min 7.0 --overall-min 6.0

Exit codes:
  0 = all thresholds met
  1 = one or more thresholds violated
  2 = analysis data not found (run projectmind analyze first)
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class Threshold:
    dimension: str
    min_score: float


@dataclass
class GateResult:
    passed: bool
    violations: list[str]
    health: dict
    diff_report: Optional[str] = None


# ---------------------------------------------------------------------------
# Core gate logic
# ---------------------------------------------------------------------------

def check_gate(
    project_path: str,
    thresholds: Optional[dict[str, float]] = None,
) -> GateResult:
    """
    Check health scores against thresholds.
    thresholds: {"overall": 6.0, "security": 7.0, "architecture": 6.0, ...}
    """
    root = Path(project_path).resolve()
    health_file = root / ".projectmind" / "health_score.json"

    if not health_file.exists():
        return GateResult(passed=False, violations=["No health data — run `projectmind analyze` first"], health={})

    health = json.loads(health_file.read_text())
    defaults = {
        "overall":         float(os.environ.get("PM_OVERALL_MIN",  "6.0")),
        "security":        float(os.environ.get("PM_SECURITY_MIN", "7.0")),
        "architecture":    float(os.environ.get("PM_ARCH_MIN",     "5.0")),
        "maintainability": float(os.environ.get("PM_MAINT_MIN",    "5.0")),
    }
    effective = {**defaults, **(thresholds or {})}

    violations: list[str] = []
    dim_map = {
        "overall":         "overall",
        "security":        "security",
        "architecture":    "architecture",
        "maintainability": "maintainability",
    }
    for key, min_val in effective.items():
        actual = health.get(dim_map.get(key, key), 0)
        if actual < min_val:
            violations.append(
                f"{key.capitalize()} score {actual:.1f} < {min_val:.1f} (threshold)"
            )

    return GateResult(passed=not violations, violations=violations, health=health)


def format_pr_comment(result: GateResult, project_name: str = "Project") -> str:
    """Format a GitHub PR comment with the gate result."""
    status = "✅ Passed" if result.passed else "❌ Failed"
    h = result.health

    lines = [
        "<!-- projectmind-gate -->",
        f"## ProjectMind Health Gate — {status}",
        "",
        "| Dimension | Score | Status |",
        "|-----------|-------|--------|",
    ]

    def _row(name: str, key: str, threshold: float = 0.0) -> str:
        val = h.get(key, 0)
        icon = "✅" if val >= threshold else "❌"
        return f"| {name} | {val:.1f}/10 | {icon} |"

    lines.append(_row("Overall",         "overall",         6.0))
    lines.append(_row("Architecture",    "architecture",    5.0))
    lines.append(_row("Security",        "security",        7.0))
    lines.append(_row("Maintainability", "maintainability", 5.0))

    if result.violations:
        lines += ["", "### ⚠ Violations", ""]
        for v in result.violations:
            lines.append(f"- {v}")

    b = h.get("breakdown", {})
    if b:
        lines += [
            "",
            "### Issues",
            f"- Security errors: **{b.get('security_errors', 0)}**",
            f"- Circular dependencies: {b.get('circular_dependencies', 0)}",
            f"- Dead functions: {b.get('dead_functions', 0)}",
            f"- High complexity: {b.get('high_complexity_functions', 0)}",
        ]

    lines += [
        "",
        "_Generated by [ProjectMind AI](https://github.com/Aaravkhanal/llm-reviewer)_",
    ]
    return "\n".join(lines)


def post_github_comment(comment: str, token: str, owner: str, repo: str, pr_number: int) -> None:
    """Post or update the gate comment on a GitHub PR."""
    import urllib.request

    _TAG = "<!-- projectmind-gate -->"
    base = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "User-Agent": "projectmind/1.0",
    }

    def _api(url: str, method: str = "GET", data: Optional[bytes] = None) -> dict:
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read())

    # Find existing comment
    existing_id: Optional[int] = None
    try:
        comments = _api(base)
        for c in comments:
            if _TAG in c.get("body", ""):
                existing_id = c["id"]
                break
    except Exception:
        pass

    payload = json.dumps({"body": comment}).encode()
    if existing_id:
        _api(f"{base[:-len('/comments')]}/comments/{existing_id}", method="PATCH", data=payload)
    else:
        _api(base, method="POST", data=payload)


# ---------------------------------------------------------------------------
# CLI entrypoint (used by GitHub Action)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--path", default=".")
    parser.add_argument("--overall-min", type=float, default=6.0)
    parser.add_argument("--security-min", type=float, default=7.0)
    parser.add_argument("--arch-min", type=float, default=5.0)
    parser.add_argument("--post-comment", action="store_true")
    parser.add_argument("--github-token", default=os.environ.get("GITHUB_TOKEN", ""))
    parser.add_argument("--owner", default=os.environ.get("GITHUB_REPOSITORY_OWNER", ""))
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "").split("/")[-1])
    parser.add_argument("--pr-number", type=int, default=int(os.environ.get("PR_NUMBER", "0")))
    args = parser.parse_args()

    result = check_gate(
        args.path,
        {"overall": args.overall_min, "security": args.security_min, "architecture": args.arch_min},
    )

    comment = format_pr_comment(result, Path(args.path).name)
    print(comment)

    if args.post_comment and args.github_token and args.pr_number:
        post_github_comment(comment, args.github_token, args.owner, args.repo, args.pr_number)
        print(f"\nPosted comment to PR #{args.pr_number}", file=sys.stderr)

    if not result.passed:
        print("\nGate FAILED:", file=sys.stderr)
        for v in result.violations:
            print(f"  {v}", file=sys.stderr)
        sys.exit(1)

    print("Gate PASSED", file=sys.stderr)
