"""
SmartPromptGenerator — converts a plain task description into a rich,
context-aware prompt that a coding agent can use without reading the codebase.

Two modes:
  template-based (default): pure Python, works offline, deterministic
  llm-enhanced (opt-in):    LLM refines and structures the final prompt
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from backend.core.compression.budget import coding_agent_budget
from backend.core.compression.compressor import Compressor


# ---------------------------------------------------------------------------
# Template builder
# ---------------------------------------------------------------------------

PROMPT_TEMPLATE = """\
# Coding Task — Context-Enriched Prompt
## Project Context

**Language:** {language}
**Frameworks:** {frameworks}
**Database:** {database}
**Authentication:** {auth}
**API Style:** {api_style}
**Architecture:** {architecture}

## Coding Conventions
{coding_style}

## Architectural Decisions (must follow)
{decisions}

## Known Pitfalls (avoid these)
{known_errors}

## Relevant Patterns in Use
{patterns}

## Critical Files to Read First
{critical_files}

## Relevant Memories
{relevant_memories}

---

## Task

{task}

---

*Generated by ProjectMind AI. Do not change the context section.*
"""


class SmartPromptGenerator:
    def __init__(self, project_path: str):
        self.root = Path(project_path)
        self.pm_dir = self.root / ".projectmind"
        self._compressor = Compressor(project_path)

    def generate(
        self,
        task: str,
        llm_enhance: bool = False,
        llm_model: Optional[str] = None,
        llm_provider: str = "openai",
        api_key: Optional[str] = None,
        k_memories: int = 5,
    ) -> dict:
        """
        Returns:
          {
            "prompt": str,              # the enriched prompt
            "context": dict,            # raw compressed context
            "relevant_memories": list,  # matched memory items
            "budget": dict,             # token budget usage
            "token_estimate": int,      # estimated total tokens
          }
        """
        budget = coding_agent_budget()
        budget.fill("task", f"## Task\n\n{task}")

        ctx_result = self._compressor.compress_with_budget(budget)
        ctx = ctx_result["context_json"]

        # Semantic search for task-relevant memories
        relevant = self._search_memories(task, k=k_memories)
        memories_text = self._format_memories(relevant)
        budget.fill("relevant_memories", memories_text)

        # Determine critical files from entry_points + architecture
        critical_files = ctx.get("entry_points", [])[:6]

        prompt = PROMPT_TEMPLATE.format(
            language=ctx.get("language", "unknown"),
            frameworks=ctx.get("frameworks", "none"),
            database=ctx.get("database", "none"),
            auth=ctx.get("authentication", "none"),
            api_style=ctx.get("api_style", "none"),
            architecture=ctx.get("architecture", "unknown"),
            coding_style=self._fmt_list(ctx.get("coding_style", [])) or "_none detected_",
            decisions=self._fmt_list(ctx.get("decisions", [])) or "_none recorded_",
            known_errors=self._fmt_list(ctx.get("known_errors", [])) or "_none recorded_",
            patterns=self._fmt_list(ctx.get("patterns", [])) or "_none detected_",
            critical_files=self._fmt_list([f"`{f}`" for f in critical_files]) or "_none_",
            relevant_memories=memories_text or "_no relevant memories found_",
            task=task,
        )

        if llm_enhance:
            prompt = self._llm_enhance(task, llm_model, llm_provider or "openai", api_key)

        # Record token savings
        try:
            from backend.core.token_stats import TokenStats, estimate_raw_tokens
            stats = TokenStats(self.pm_dir)
            raw = estimate_raw_tokens(self.root)
            stats.record(
                tokens_used=budget.usage_report["used"],
                raw_codebase_tokens=raw,
                tool="generate-prompt",
            )
        except Exception:
            pass

        return {
            "prompt": prompt,
            "context": ctx,
            "relevant_memories": relevant,
            "budget": budget.usage_report,
            "token_estimate": budget.usage_report["used"],
        }

    # ------------------------------------------------------------------

    def _search_memories(self, query: str, k: int) -> list[dict]:
        db_path = self.pm_dir / "memory.db"
        if not db_path.exists():
            return []
        try:
            from backend.core.memory.store import MemoryStore
            store = MemoryStore(str(db_path), enable_vectors=True)
            store.init_db()
            return store.search(query, k=k)
        except Exception:
            return []

    def _format_memories(self, memories: list[dict]) -> str:
        if not memories:
            return ""
        lines = []
        for m in memories:
            score = m.get("score", 0)
            label = f"[{m['type']}]" + (f" (relevance: {score:.2f})" if score else "")
            lines.append(f"{label}\n{m['content']}")
        return "\n\n".join(lines)

    @staticmethod
    def _fmt_list(items: list[str]) -> str:
        return "\n".join(f"- {i}" for i in items) if items else ""

    def _llm_enhance(
        self,
        task: str,
        model: Optional[str],
        provider: str,
        api_key: Optional[str],
    ) -> str:
        import os
        from langchain_core.output_parsers import StrOutputParser
        from backend.llm.providers import LLM, LLMProvider, PromptTemplate

        lm = LLM(
            model_name=model or os.environ.get("CONVERSATION_MODEL", "gpt-4o-mini"),
            provider=LLMProvider(provider),
            api_key=api_key,
        )
        assert lm.model is not None
        template = LLM.load_prompt(PromptTemplate.SMART_PROMPT)
        chain = template | lm.model | StrOutputParser()

        ctx_json = json.dumps(self._compressor.compress(), indent=2)
        return chain.invoke({"project_context": ctx_json[:4000], "task": task})
