"""
BYOK (Bring Your Own Keys) schema.

ProviderKey   — encrypted API keys per project + provider
ModelProfile  — benchmark results: latency, quality, cost per task type
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlmodel import Field, SQLModel


SUPPORTED_PROVIDERS = [
    # Cloud
    "openai", "anthropic", "google", "groq", "deepseek",
    "openrouter", "together", "mistral", "xai", "fireworks",
    "azure", "bedrock", "huggingface",
    # Local
    "ollama", "lmstudio", "vllm", "llamacpp",
    # NVIDIA NIM (already integrated)
    "nvidia",
]

PROVIDER_METADATA: dict[str, dict] = {
    "openai":      {"label": "OpenAI",       "base_url": "https://api.openai.com/v1",           "key_env": "OPENAI_API_KEY",    "models": ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1", "o3-mini"]},
    "anthropic":   {"label": "Anthropic",    "base_url": "https://api.anthropic.com",            "key_env": "ANTHROPIC_API_KEY", "models": ["claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"]},
    "google":      {"label": "Google Gemini","base_url": "https://generativelanguage.googleapis.com", "key_env": "GEMINI_API_KEY", "models": ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-1.5-pro"]},
    "groq":        {"label": "Groq",         "base_url": "https://api.groq.com/openai/v1",       "key_env": "GROQ_API_KEY",      "models": ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"]},
    "deepseek":    {"label": "DeepSeek",     "base_url": "https://api.deepseek.com",             "key_env": "DEEPSEEK_API_KEY",  "models": ["deepseek-chat", "deepseek-reasoner"]},
    "openrouter":  {"label": "OpenRouter",   "base_url": "https://openrouter.ai/api/v1",         "key_env": "OPENROUTER_API_KEY","models": ["auto"]},
    "together":    {"label": "Together AI",  "base_url": "https://api.together.xyz/v1",          "key_env": "TOGETHER_API_KEY",  "models": ["meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"]},
    "mistral":     {"label": "Mistral",      "base_url": "https://api.mistral.ai/v1",            "key_env": "MISTRAL_API_KEY",   "models": ["mistral-large-latest", "mistral-small-latest", "codestral-latest"]},
    "xai":         {"label": "xAI Grok",     "base_url": "https://api.x.ai/v1",                 "key_env": "XAI_API_KEY",       "models": ["grok-3", "grok-3-mini"]},
    "fireworks":   {"label": "Fireworks",    "base_url": "https://api.fireworks.ai/inference/v1","key_env": "FIREWORKS_API_KEY", "models": ["accounts/fireworks/models/llama-v3p3-70b-instruct"]},
    "nvidia":      {"label": "NVIDIA NIM",   "base_url": "https://integrate.api.nvidia.com/v1",  "key_env": "NVIDIA_API_KEY",    "models": ["meta/llama-3.1-70b-instruct", "deepseek/deepseek-r1"]},
    "ollama":      {"label": "Ollama",       "base_url": "http://localhost:11434",               "key_env": None,                "models": ["llama3.2", "qwen2.5-coder", "deepseek-coder-v2", "gemma3"]},
    "lmstudio":    {"label": "LM Studio",    "base_url": "http://localhost:1234/v1",             "key_env": None,                "models": []},
    "vllm":        {"label": "vLLM",         "base_url": "http://localhost:8000/v1",             "key_env": None,                "models": []},
    "huggingface": {"label": "HuggingFace",  "base_url": "https://api-inference.huggingface.co","key_env": "HUGGINGFACE_API_KEY","models": []},
}


class ProviderKey(SQLModel, table=True):
    __tablename__ = "provider_key"  # type: ignore[assignment]

    id: Optional[int] = Field(default=None, primary_key=True)
    project_path: str = Field(index=True)
    provider: str = Field(index=True)          # "openai" | "anthropic" | etc.

    encrypted_key: Optional[str] = None        # Fernet-encrypted API key (None for local providers)
    base_url_override: Optional[str] = None    # Custom endpoint (e.g. Azure, self-hosted vLLM)
    is_active: bool = Field(default=True)

    # Last health check
    health_status: str = Field(default="unknown")   # ok | error | untested
    health_message: Optional[str] = None
    last_tested_at: Optional[datetime] = None

    # Available models discovered during test/benchmark
    available_models_json: Optional[str] = None    # JSON list

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class ModelProfile(SQLModel, table=True):
    """
    Benchmark results for a specific model on a specific task type.
    Generated by ModelProfiler when a user adds API keys.
    """
    __tablename__ = "model_profile"  # type: ignore[assignment]

    id: Optional[int] = Field(default=None, primary_key=True)
    project_path: str = Field(index=True)
    provider: str
    model_id: str = Field(index=True)

    # Task scores (0–10, null = not benchmarked)
    score_code_review: Optional[float] = None
    score_architecture: Optional[float] = None
    score_security: Optional[float] = None
    score_documentation: Optional[float] = None
    score_bug_fix: Optional[float] = None
    score_testing: Optional[float] = None
    score_refactor: Optional[float] = None
    score_reasoning: Optional[float] = None

    # Performance metrics
    avg_latency_ms: Optional[float] = None
    context_window: Optional[int] = None
    cost_per_1k_input: Optional[float] = None
    cost_per_1k_output: Optional[float] = None

    # Capability flags
    supports_tools: bool = Field(default=False)
    supports_vision: bool = Field(default=False)
    supports_streaming: bool = Field(default=True)

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
